import pytest

def find_the_difference():
    """
    Finds the extra character in string `t` that was added to string `s`.

    String `t` is generated by shuffling string `s` and adding one extra character at a random position.
    The task is to identify that added character.

    Args:
        s (str): The original string.
        t (str): The modified string with one extra character.

    Returns:
        str: The character that was added to `t`.
    """

    pass

def test_find_the_difference():
    result = find_the_difference()
    assert result is None  # TODO: update assertion

if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__]))
